-- 코드를 작성해주세요
SELECT hg.EMP_NO, he.EMP_NAME, CASE WHEN( AVG(SCORE) >= 96 ) THEN 'S' WHEN( AVG(SCORE) >= 90 ) THEN 'A' WHEN( AVG(SCORE) >= 80 ) THEN 'B' ELSE 'C' END AS GRADE, CASE WHEN( AVG(SCORE) >= 96 ) THEN he.SAL * 0.2 WHEN ( AVG(SCORE) >= 90 ) THEN he.SAL * 0.15 WHEN ( AVG(SCORE) >= 80 ) THEN he.SAL * 0.1 ELSE 0 END AS BONUS
FROM HR_GRADE hg JOIN HR_EMPLOYEES he ON he.EMP_NO = hg.EMP_NO
GROUP BY hg.EMP_NO, he.EMP_NAME
ORDER BY hg.EMP_NO
